### ISSUE TITLE
error

### ISSUE THREAD

**Issue by iewuirq** [lovac42/HoochieBaby#11]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.32 (dee7d45d) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.7
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-09-28 00:13:13
Add-ons possibly involved: ⁨HoochieBaby Queue Controller  Day-Lrn Q⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/main.py", line 997, in onStudyKey
  File "aqt/main.py", line 661, in moveToState
  File "aqt/main.py", line 683, in _reviewState
  File "aqt/reviewer.py", line 65, in show
  File "aqt/reviewer.py", line 110, in nextCard
  File "anki/schedv2.py", line 63, in getCard
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-46>", line 2, in _getCard
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 635, in repl
  File "/Users/dorischan/Library/Application Support/Anki2/addons21/1847358755/hoochieBaby.py", line 54, in getCard
    return _old(self)
  File "anki/schedv2.py", line 284, in _getCard
  File "anki/schedv2.py", line 331, in _getNewCard
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-22>", line 2, in _fillNew
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 635, in repl
TypeError: fillNew() got multiple values for argument '_old'

**Comment by lovac42** [comment]
This should not be related to hoochieBaby, probably another addon.
