### ISSUE TITLE
Error Appears When Reviewing

### ISSUE THREAD

**Issue by Kosezu** [lovac42/HoochieBaby#12]
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-10-23 12:59:09

Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-10-23 12:59:09

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 493, in handler
  File "aqt\reviewer.py", line 331, in _onAnswerButton
  File "C:\Users\ykama\AppData\Roaming\Anki2\addons21\PassFailJP\__init__.py", line 41, in AKR_answerCard
    __oldFunc(self, ease)
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-10>", line 2, in _answerCard
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 633, in repl
  File "aqt\reviewer.py", line 269, in _answerCard
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-172>", line 2, in nextCard
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 629, in repl
  File "aqt\reviewer.py", line 110, in nextCard
  File "anki\schedv2.py", line 63, in getCard
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-114>", line 2, in _getCardReorderedv2
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 635, in repl
  File "C:\Users\ykama\AppData\Roaming\Anki2\addons21\1847358755\hoochieBaby.py", line 49, in getCard
    c = self._getNewCard()
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-96>", line 2, in _getNewCard
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 635, in repl
  File "C:\Users\ykama\AppData\Roaming\Anki2\addons21\1797395052\pushParadox.py", line 46, in getNewCard
    if not sched._newQueue and sched._fillNew():
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-20>", line 2, in _fillNew
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 635, in repl
TypeError: fillNew() got multiple values for argument '_old'

**Comment by lovac42** [comment]
This should not be related to hoochie baby, probably pushParadox or hoochiePapa. I'll look into those later.
